config/routes.rb
# config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  authenticated :user do
    root 'financial_records#index', as: :authenticated_root
    resources :financial_records
  end

  devise_scope :user do
    root to: "devise/sessions#new" # Use devise/sessions#new as the root for unauthenticated users
    delete 'sign_out', to: 'devise/sessions#destroy' # No need to explicitly name it
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/financial_record.rb
class FinancialRecord < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
# app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  protect_from_forgery with: :exception

  # Any other common functionality or configurations for your controllers can go here
end

app/controllers/financial_records_controller.rb
class FinancialRecordsController < ApplicationController
  before_action :set_financial_record, only: %i[show edit update destroy]

  def index
    @financial_records = FinancialRecord.all
  end

  def show
  end

  def new
    @financial_record = FinancialRecord.new
  end

  def create
    @financial_record = FinancialRecord.new(financial_record_params)

    if @financial_record.save
      redirect_to financial_records_path, notice: 'Financial record was successfully created.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @financial_record.update(financial_record_params)
      redirect_to financial_records_path, notice: 'Financial record was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @financial_record.destroy
    redirect_to financial_records_path, notice: 'Financial record was successfully destroyed.'
  end

  private

  def set_financial_record
    @financial_record = FinancialRecord.find(params[:id])
  end

  def financial_record_params
    params.require(:financial_record).permit(:name, :amount, :date)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/financial_records_helper.rb
module FinancialRecordsHelper
end

app/views/financial_records/_form.html.erb
<%= form_with(model: @financial_record, local: true) do |form| %>
  <div class="form-container">

    <% if @financial_record.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@financial_record.errors.count, 'error') %> prohibited this financial record from being saved:</h2>

        <ul>
          <% @financial_record.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-field">
      <%= form.label :name %>
      <%= form.text_field :name %>
    </div>

    <div class="form-field">
      <%= form.label :amount %>
      <%= form.text_field :amount %>
    </div>

    <div class="form-field">
      <%= form.label :date %>
      <%= form.date_field :date %>
    </div>

    <div class="form-actions">
      <%= form.submit class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/financial_records/edit.html.erb
<div class="financial-record-edit-container">
  <h1 class ="custom-login-page h2">Edit Financial Record</h1>

  <%= render 'form' %>

  <div class="action-links">
    <%= link_to 'Show', @financial_record, class: 'btn btn-secondary' %> |
    <%= link_to 'Back', financial_records_path, class: 'btn btn-primary' %>
  </div>
</div>

app/views/financial_records/index.html.erb
<% if user_signed_in? %>
  <div class="user-welcome">
    <p>Welcome, <%= current_user.email %>!</p>
  </div>
<% end %>

<div class="financial-records-container">
  <h1>Financial Records</h1>

  <%= link_to 'New Financial Record', new_financial_record_path, class: 'btn btn-primary' %>

  <table class="financial-records-table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Amount</th>
        <th>Date</th>
        <th colspan="3">Actions</th>
      </tr>
    </thead>

    <tbody>
      <% @financial_records.each do |financial_record| %>
        <tr>
          <td><%= financial_record.name %></td>
          <td><%= financial_record.amount %></td>
          <td><%= financial_record.date %></td>
          <td><%= link_to 'Show', financial_record, class: 'btn btn-secondary' %></td>
          <td><%= link_to 'Edit', edit_financial_record_path(financial_record), class: 'btn btn-warning' %></td>
          <td><%= link_to 'Destroy', financial_record, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/financial_records/new.html.erb
<div class="financial-record-edit-container">
  <h1>New Financial Record</h1>

  <div class="form-container">
    <%= render 'form' %>
  </div>

  <div class="action-links">
    <%= link_to 'Back', financial_records_path, class: 'btn btn-warning' %>
  </div>
</div>

app/views/financial_records/show.html.erb
<div class="financial-record-edit-container">
<h1 class ="custom-login-page h2">Financial Record</h1>

    <p>
    <strong>Name:</strong>
    <%= @financial_record.name %>
    </p>

    <p>
    <strong>Amount:</strong>
    <%= @financial_record.amount %>
    </p>

    <p>
    <strong>Date:</strong>
    <%= @financial_record.date %>
    </p>

    <div class="action-links">
        <%= link_to 'Edit', edit_financial_record_path(@financial_record),class: 'btn btn-warning' %> |
        <%= link_to 'Back', financial_records_path,class: 'btn btn-primary' %>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FinancialRecords</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>